### ISSUE TITLE
Use Cocoapods for libraries

### ISSUE THREAD

**Issue by CameronBanga** [jpsim/CardsAgainst#1]
Would be nice for quickly cloning and then building.

**Comment by ammar-wizsoft** [comment]
First command gives 
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
Kindly guide me downloading libraries with git. I am unable to run the project.

**Comment by jpsim** [comment]
Looks like it was moved https://github.com/SVProgressHUD/SVProgressHUD
