### ISSUE TITLE
Project won't build

### ISSUE THREAD

**Issue by Deco354** [jpsim/CardsAgainst#13]
I can't build the project upon cloning, I get the following errors. Only changes I've made were to change the package name in as I couldn't build with the original package name using my personal development team.

![image](https://user-images.githubusercontent.com/18557720/35473699-2c1613c0-0384-11e8-89c0-93622614da77.png)

**Comment by coopersita** [comment]
You need to download the 3 libraries the project uses and add them to your project (links are on the Read me file).

**Comment by Deco354** [comment]
Thanks, apologies for the nooby question.
