### ISSUE TITLE
White card text not visible when dark mode is enabled

### ISSUE THREAD

**Issue by jayson528** [jpsim/CardsAgainst#16]
Hey, i noticed that the WhiteCard text is not visible when dark mode is enabled in iOS 13. The label textColor for the WhiteCards was never set, so by default it will turn white with dark mode enabled.

Im going to submit a PR for the fix in about 5 minutes.

Dark mode disabled:
![image](https://user-images.githubusercontent.com/42183771/67506465-15389f80-f65b-11e9-874a-3a1bc5930a41.png)

Dark mode enabled: 
![image](https://user-images.githubusercontent.com/42183771/67506510-28e40600-f65b-11e9-9ba6-2d5e11e368f8.png)

**Comment by jpsim** [comment]
I'm amazed someone out there is still running this 😆

**Comment by jayson528** [comment]
To be completely honest with you i'm doing these for school and i was trying to replicate the other bugs and by complete accident stumbled upon it. Do you mind if i make a separate PR to fix the constraints to fit the iPhone 10 display? @jpsim

**Comment by jpsim** [comment]
Fixed in #17.
