### ISSUE TITLE
Build failed in Xcode 7.2.1

### ISSUE THREAD

**Issue by dpmusic** [jpsim/CardsAgainst#7]
Hi JP, thanks for your email reply! Yes I would love to get cards running! 

but I just downloaded your latest version, and still cannot get it to build successfully for the iPhone 6 simulator. I'm a total noob, so could well be missing something totally obvious. I've attached a screen grab of the error list I get-

<img width="257" alt="cards errors" src="https://cloud.githubusercontent.com/assets/17975245/13929125/d7a0dc1a-ef55-11e5-80ea-bedfe6290575.png">

**Comment by jpsim** [comment]
This project uses git submodules, make you you have them before trying to build!

```
git submodule update --init --recursive
```
